### ISSUE TITLE
Style - Move & Style Search Bar

### ISSUE THREAD

**Issue by lexoskeleton** [lexoskeleton/feq_dictionary_app#13]

**Comment by lexoskeleton** [comment]
We need to move our search bar to render below our top navbar, and style it according to the example from Figma:


![Image](https://github.com/lexoskeleton/feq_dictionary_app/assets/9019265/a8a14c27-21fb-46b2-9338-225c8875bf90)

**Comment by knopgm** [comment]
Already done in the issue #35
